import{i as d,a as S,S as w}from"./assets/vendor-64b55ca9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const s={form:document.querySelector("form"),inputSearch:document.querySelector("input"),imageContainer:document.querySelector(".gallery"),loader:document.querySelector(".loader"),btnLoadMore:document.querySelector(".btn")};function f(){s.loader.classList.remove("hidden")}function g(){s.loader.classList.add("hidden")}function p(){d.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}async function h(r,t){const a="42120436-8d9fae2eb5c6f9f50c8ac4324",o="https://pixabay.com/api/",i={key:a,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await S.get(o,{params:i})).data}function M(r){const{largeImageURL:t,webformatURL:a,tags:l,likes:e,views:o,comments:i,downloads:m}=r;return`<li class="gallery-item">
            <a class="gallery-link" href="${t}">
              <img class="gallery-image" src="${a}" alt="${l}" />
            </a>
              <ul class="list-content">      
                  <li class="list-text"><p>Likes <span>${e}</span></p></li>
                  <li class="list-text"><p>Views <span>${o}</span></p></li>
                  <li class="list-text"><p>Comments <span>${i}</span></p></li>
                  <li class="list-text"><p>Downloads <span>${m}</span></p></li>
              </ul>
          </li>`}function q(r){return r.map(M).join("")}let c,n,u,y=new w(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250});async function v(r){if(r.preventDefault(),c=r.target.elements.query.value.trim(),s.imageContainer.innerHTML="",n=1,!c){s.btnLoadMore.classList.add("hidden"),d.warning({message:"This field cannot be empty!!!",position:"topRight"});return}f();try{const t=await h(c,n);t.hits.length||p(),u=Math.ceil(t.totalHits/15),s.imageContainer.innerHTML="",L(t.hits),y.refresh()}catch{p()}g(),b(),r.target.reset()}async function E(r){r.preventDefault(),n+=1,f();const t=await h(c,n);L(t.hits),y.refresh(),g(),b(),n>=u&&d.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomRight"});const a=s.imageContainer.firstElementChild.getBoundingClientRect().height;scrollBy({top:a*2,behavior:"smooth"})}function L(r){const t=q(r);s.imageContainer.insertAdjacentHTML("beforeend",t)}function b(){n>=u?s.btnLoadMore.classList.add("hidden"):s.btnLoadMore.classList.remove("hidden")}s.form.addEventListener("submit",v);s.btnLoadMore.addEventListener("click",E);
//# sourceMappingURL=commonHelpers.js.map
